#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# api_login_check:
#     path: /api/login_check
# controllers:
#     resource: '../src/Controller/'
#     type:     annotation
