<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.hD5blFV' shared service.

return $this->privates['.service_locator.hD5blFV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'userPrestataireRepository' => ['privates', 'App\\Repository\\UserPrestataireRepository', 'getUserPrestataireRepositoryService.php', true],
], [
    'userPrestataireRepository' => 'App\\Repository\\UserPrestataireRepository',
]);
