<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Lv0DYBX' shared service.

return $this->privates['.service_locator.Lv0DYBX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'userPrestataire' => ['privates', '.errored..service_locator.Lv0DYBX.App\\Entity\\UserPrestataire', NULL, 'Cannot autowire service ".service_locator.Lv0DYBX": it references class "App\\Entity\\UserPrestataire" but no such service exists.'],
], [
    'userPrestataire' => 'App\\Entity\\UserPrestataire',
]);
