<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Pw6r5KN' shared service.

return $this->privates['.service_locator.Pw6r5KN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'caissierRepository' => ['privates', 'App\\Repository\\CaissierRepository', 'getCaissierRepositoryService.php', true],
], [
    'caissierRepository' => 'App\\Repository\\CaissierRepository',
]);
