<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..AAHuhQ' shared service.

return $this->privates['.service_locator..AAHuhQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'caissier' => ['privates', '.errored..service_locator..AAHuhQ.App\\Entity\\Caissier', NULL, 'Cannot autowire service ".service_locator..AAHuhQ": it references class "App\\Entity\\Caissier" but no such service exists.'],
], [
    'caissier' => 'App\\Entity\\Caissier',
]);
