<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.sY7k4go' shared service.

return $this->privates['.service_locator.sY7k4go'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CaissierController::delete' => ['privates', '.service_locator..AAHuhQ', 'get_ServiceLocator__AAHuhQService.php', true],
    'App\\Controller\\CaissierController::edit' => ['privates', '.service_locator..AAHuhQ', 'get_ServiceLocator__AAHuhQService.php', true],
    'App\\Controller\\CaissierController::index' => ['privates', '.service_locator.Pw6r5KN', 'get_ServiceLocator_Pw6r5KNService.php', true],
    'App\\Controller\\CaissierController::show' => ['privates', '.service_locator..AAHuhQ', 'get_ServiceLocator__AAHuhQService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\CaissierController:delete' => ['privates', '.service_locator..AAHuhQ', 'get_ServiceLocator__AAHuhQService.php', true],
    'App\\Controller\\CaissierController:edit' => ['privates', '.service_locator..AAHuhQ', 'get_ServiceLocator__AAHuhQService.php', true],
    'App\\Controller\\CaissierController:index' => ['privates', '.service_locator.Pw6r5KN', 'get_ServiceLocator_Pw6r5KNService.php', true],
    'App\\Controller\\CaissierController:show' => ['privates', '.service_locator..AAHuhQ', 'get_ServiceLocator__AAHuhQService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
], [
    'App\\Controller\\CaissierController::delete' => '?',
    'App\\Controller\\CaissierController::edit' => '?',
    'App\\Controller\\CaissierController::index' => '?',
    'App\\Controller\\CaissierController::show' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\CaissierController:delete' => '?',
    'App\\Controller\\CaissierController:edit' => '?',
    'App\\Controller\\CaissierController:index' => '?',
    'App\\Controller\\CaissierController:show' => '?',
    'App\\Controller\\SecurityController:register' => '?',
]);
