<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.OJA0DYz' shared service.

return $this->privates['.service_locator.OJA0DYz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CaissierController::delete' => ['privates', '.service_locator..AAHuhQ', 'get_ServiceLocator__AAHuhQService.php', true],
    'App\\Controller\\CaissierController::edit' => ['privates', '.service_locator..AAHuhQ', 'get_ServiceLocator__AAHuhQService.php', true],
    'App\\Controller\\CaissierController::new' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\CaissierController::show' => ['privates', '.service_locator..AAHuhQ', 'get_ServiceLocator__AAHuhQService.php', true],
    'App\\Controller\\DepotController::delete' => ['privates', '.service_locator.E3DK7HO', 'get_ServiceLocator_E3DK7HOService.php', true],
    'App\\Controller\\DepotController::edit' => ['privates', '.service_locator.E3DK7HO', 'get_ServiceLocator_E3DK7HOService.php', true],
    'App\\Controller\\DepotController::index' => ['privates', '.service_locator.VzTiFkg', 'get_ServiceLocator_VzTiFkgService.php', true],
    'App\\Controller\\DepotController::new' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\DepotController::show' => ['privates', '.service_locator.E3DK7HO', 'get_ServiceLocator_E3DK7HOService.php', true],
    'App\\Controller\\SecurityController::bloquer' => ['privates', '.service_locator.28.2M_B', 'get_ServiceLocator_28_2MBService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\CaissierController:delete' => ['privates', '.service_locator..AAHuhQ', 'get_ServiceLocator__AAHuhQService.php', true],
    'App\\Controller\\CaissierController:edit' => ['privates', '.service_locator..AAHuhQ', 'get_ServiceLocator__AAHuhQService.php', true],
    'App\\Controller\\CaissierController:new' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\CaissierController:show' => ['privates', '.service_locator..AAHuhQ', 'get_ServiceLocator__AAHuhQService.php', true],
    'App\\Controller\\DepotController:delete' => ['privates', '.service_locator.E3DK7HO', 'get_ServiceLocator_E3DK7HOService.php', true],
    'App\\Controller\\DepotController:edit' => ['privates', '.service_locator.E3DK7HO', 'get_ServiceLocator_E3DK7HOService.php', true],
    'App\\Controller\\DepotController:index' => ['privates', '.service_locator.VzTiFkg', 'get_ServiceLocator_VzTiFkgService.php', true],
    'App\\Controller\\DepotController:new' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\DepotController:show' => ['privates', '.service_locator.E3DK7HO', 'get_ServiceLocator_E3DK7HOService.php', true],
    'App\\Controller\\SecurityController:bloquer' => ['privates', '.service_locator.28.2M_B', 'get_ServiceLocator_28_2MBService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
], [
    'App\\Controller\\CaissierController::delete' => '?',
    'App\\Controller\\CaissierController::edit' => '?',
    'App\\Controller\\CaissierController::new' => '?',
    'App\\Controller\\CaissierController::show' => '?',
    'App\\Controller\\DepotController::delete' => '?',
    'App\\Controller\\DepotController::edit' => '?',
    'App\\Controller\\DepotController::index' => '?',
    'App\\Controller\\DepotController::new' => '?',
    'App\\Controller\\DepotController::show' => '?',
    'App\\Controller\\SecurityController::bloquer' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\CaissierController:delete' => '?',
    'App\\Controller\\CaissierController:edit' => '?',
    'App\\Controller\\CaissierController:new' => '?',
    'App\\Controller\\CaissierController:show' => '?',
    'App\\Controller\\DepotController:delete' => '?',
    'App\\Controller\\DepotController:edit' => '?',
    'App\\Controller\\DepotController:index' => '?',
    'App\\Controller\\DepotController:new' => '?',
    'App\\Controller\\DepotController:show' => '?',
    'App\\Controller\\SecurityController:bloquer' => '?',
    'App\\Controller\\SecurityController:register' => '?',
]);
