<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXa6EdOG\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXa6EdOG/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXa6EdOG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXa6EdOG\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerXa6EdOG\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'Xa6EdOG',
    'container.build_id' => 'f834644a',
    'container.build_time' => 1565018312,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXa6EdOG');
