<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJPSfdrS\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJPSfdrS/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJPSfdrS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJPSfdrS\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerJPSfdrS\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'JPSfdrS',
    'container.build_id' => 'c8217511',
    'container.build_time' => 1565079386,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJPSfdrS');
