<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYTKuuFX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYTKuuFX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYTKuuFX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYTKuuFX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYTKuuFX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YTKuuFX',
    'container.build_id' => '4a56c7a8',
    'container.build_time' => 1564968836,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYTKuuFX');
