<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXdHEnBs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXdHEnBs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXdHEnBs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXdHEnBs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXdHEnBs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XdHEnBs',
    'container.build_id' => '96071b9b',
    'container.build_time' => 1565016652,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXdHEnBs');
