<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTARzld2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTARzld2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTARzld2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTARzld2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTARzld2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TARzld2',
    'container.build_id' => 'b6e2e15c',
    'container.build_time' => 1572006954,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTARzld2');
